/*** Compiler Front-End Test automatically generated by the BNF Converter ***/   
/*                                                                          */
/* This test will parse a file, print the abstract syntax tree, and then    */
/* pretty-print the result.                                                 */
/*                                                                          */
/****************************************************************************/
#include <stdio.h>
#include "Runtime.H"


using namespace std;

int main(int argc, char ** argv)
{
  Runtime *g = new Runtime();
  DEB("Initializing data");
  g->initialize("saved_data");
  DEB("Data initialized");
  DEB("Starting execution");
  g->run();
  DEB("Execution finished");
  
  return 1;
}

