/*** Compiler Front-End Test automatically generated by the BNF Converter ***/   
/*                                                                          */
/* This test will parse a file, print the abstract syntax tree, and then    */
/* pretty-print the result.                                                 */
/*                                                                          */
/****************************************************************************/
#include <stdio.h>
#include "Runtime.H"

using namespace std;

int main(int argc, char ** argv)
{
  Runtime *g = new Runtime();
  cout << "Initializing data" << endl;
  g->initialize("saved_data");
  cout << "Data initialized" << endl;
  cout << "Starting execution" << endl;
  g->run();
  cout << "Execution finished" << endl;
  
  return 1;
}

